In [2]:
import pandas as pd 
import numpy as np 
data = ({
    "Student":["Alice","Bob","Charlie","David","Rohit","Agastya","Amar","Joy"],
    "Maths":[85,90,np.nan,92,88,95,80,91],
    "Science":[80,85,90,np.nan,88,92,np.nan,89],
    "English":[75,80,85,90,88,90,84,89],
    "Sanskrit":[70,75,np.nan,85,88,90,82,87],
    "Attendance":[90,85,95,80,88,np.nan,84,89]
})

df = pd.DataFrame(data)
df

   Student  Maths  Science  English  Sanskrit  Attendance
0    Alice   85.0     80.0       75      70.0        90.0
1      Bob   90.0     85.0       80      75.0        85.0
2  Charlie    NaN     90.0       85       NaN        95.0
3    David   92.0      NaN       90      85.0        80.0
4    Rohit   88.0     88.0       88      88.0        88.0
5  Agastya   95.0     92.0       90      90.0         NaN
6     Amar   80.0      NaN       84      82.0        84.0
7      Joy   91.0     89.0       89      87.0        89.0

#### isnull

In [3]:
df.isnull().sum()

Student       0
Maths         1
Science       2
English       0
Sanskrit      1
Attendance    1
dtype: int64

#### missing values without  mean

In [4]:
Maths_avg = df["Maths"].sum() / df["Maths"].count()
df["Maths"] = df["Maths"].fillna(Maths_avg)
df

   Student      Maths  Science  English  Sanskrit  Attendance
0    Alice  85.000000     80.0       75      70.0        90.0
1      Bob  90.000000     85.0       80      75.0        85.0
2  Charlie  88.714286     90.0       85       NaN        95.0
3    David  92.000000      NaN       90      85.0        80.0
4    Rohit  88.000000     88.0       88      88.0        88.0
5  Agastya  95.000000     92.0       90      90.0         NaN
6     Amar  80.000000      NaN       84      82.0        84.0
7      Joy  91.000000     89.0       89      87.0        89.0

#### missing values verification

In [5]:
df.isnull().sum()

Student       0
Maths         0
Science       2
English       0
Sanskrit      1
Attendance    1
dtype: int64

#### remove rows more than 2 Nan value

In [6]:
df = df[df.isnull().sum(axis=1) <= 2]
df

   Student      Maths  Science  English  Sanskrit  Attendance
0    Alice  85.000000     80.0       75      70.0        90.0
1      Bob  90.000000     85.0       80      75.0        85.0
2  Charlie  88.714286     90.0       85       NaN        95.0
3    David  92.000000      NaN       90      85.0        80.0
4    Rohit  88.000000     88.0       88      88.0        88.0
5  Agastya  95.000000     92.0       90      90.0         NaN
6     Amar  80.000000      NaN       84      82.0        84.0
7      Joy  91.000000     89.0       89      87.0        89.0