In [5]:
import pandas as pd 
data = {
    "players":["virat","rohith","sehwag","dhoni","virat","rohith","sehwag","dhoni"],
    "matches":[100,200,300,400,100,200,300,400],
    "runs":[154,200,123,145,257,309,198,128],
    "balls":[50,100,120,120,150,80,120,100]
}
ipl=pd.DataFrame(data)
ipl

  players  matches  runs  balls
0   virat      100   154     50
1  rohith      200   200    100
2  sehwag      300   123    120
3   dhoni      400   145    120
4   virat      100   257    150
5  rohith      200   309     80
6  sehwag      300   198    120
7   dhoni      400   128    100

In [6]:
ipl["strik_rate"]=(ipl["runs"]/ipl["balls"])*100
ipl

  players  matches  runs  balls  strik_rate
0   virat      100   154     50  308.000000
1  rohith      200   200    100  200.000000
2  sehwag      300   123    120  102.500000
3   dhoni      400   145    120  120.833333
4   virat      100   257    150  171.333333
5  rohith      200   309     80  386.250000
6  sehwag      300   198    120  165.000000
7   dhoni      400   128    100  128.000000

In [7]:
ipl=ipl.loc[(ipl["players"]=="virat")&(ipl["runs"]>150)]
ipl

  players  matches  runs  balls  strik_rate
0   virat      100   154     50  308.000000
4   virat      100   257    150  171.333333

In [10]:
grp=df.groupby("players")["runs"].sum()
print(grp)

players
dhoni     273
rohith    509
sehwag    321
virat     411
Name: runs, dtype: int64

In [12]:
grp=df.groupby(["players","matches"])["runs"].sum()
print(grp)

players  matches
dhoni    400        273
rohith   200        509
sehwag   300        321
virat    100        411
Name: runs, dtype: int64

In [21]:
summs=df.groupby("players").agg(
    Total_runs=("runs","sum"),
    average_runs=("runs","mean"),
    matches_played=("matches","sum"),
    highest_score=("runs","max"),
    lowest_score=("runs","min"),
    total_balls=("balls","sum"),
    fifties=("runs",lambda x:((x>=50) & (x<100)).sum())
)

summs

,Total_runs,average_runs,matches_played,highest_score,lowest_score,total_balls,fifties
players,,,,,,,
dhoni,273,136.5,800,145,128,220,0
rohith,509,254.5,400,309,200,180,0
sehwag,321,160.5,600,198,123,240,0
virat,411,205.5,200,257,154,200,0