In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("riturajsingh99/netflix-userbase")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/riturajsingh99/netflix-userbase/1.archive...

100%|██████████| 25.1k/25.1k [00:00<00:00, 22.5MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/riturajsingh99/netflix-userbase/versions/1

In [2]:
import pandas as pd
import numpy as np
import os
dataset_path = os.path.join(path, 'Netflix Userbase.csv')

df = pd.read_csv(dataset_path)
df

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month
...,...,...,...,...,...,...,...,...,...,...
2495,2496,Premium,14,25-07-22,12-07-23,Spain,28,Female,Smart TV,1 Month
2496,2497,Basic,15,04-08-22,14-07-23,Spain,33,Female,Smart TV,1 Month
2497,2498,Standard,12,09-08-22,15-07-23,United States,38,Male,Laptop,1 Month
2498,2499,Standard,13,12-08-22,12-07-23,Canada,48,Female,Tablet,1 Month
2499,2500,Basic,15,13-08-22,12-07-23,United States,35,Female,Smart TV,1 Month

In [3]:
display(df.head())
display(df.tail())

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
2495,2496,Premium,14,25-07-22,12-07-23,Spain,28,Female,Smart TV,1 Month
2496,2497,Basic,15,04-08-22,14-07-23,Spain,33,Female,Smart TV,1 Month
2497,2498,Standard,12,09-08-22,15-07-23,United States,38,Male,Laptop,1 Month
2498,2499,Standard,13,12-08-22,12-07-23,Canada,48,Female,Tablet,1 Month
2499,2500,Basic,15,13-08-22,12-07-23,United States,35,Female,Smart TV,1 Month

In [4]:
print(df.shape)
df.info()

(2500, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User ID            2500 non-null   int64
 1   Subscription Type  2500 non-null   object
 2   Monthly Revenue    2500 non-null   int64
 3   Join Date          2500 non-null   object
 4   Last Payment Date  2500 non-null   object
 5   Country            2500 non-null   object
 6   Age                2500 non-null   int64
 7   Gender             2500 non-null   object
 8   Device             2500 non-null   object
 9   Plan Duration      2500 non-null   object
dtypes: int64(3), object(7)
memory usage: 195.4+ KB

In [5]:
print(df.dtypes)
print(df.isna().sum())

User ID               int64
Subscription Type    object
Monthly Revenue       int64
Join Date            object
Last Payment Date    object
Country              object
Age                   int64
Gender               object
Device               object
Plan Duration        object
dtype: object
User ID              0
Subscription Type    0
Monthly Revenue      0
Join Date            0
Last Payment Date    0
Country              0
Age                  0
Gender               0
Device               0
Plan Duration        0
dtype: int64

In [6]:
df.rename(columns={
    "User ID": "user_id",
    "Age": "age",
    "Subscription Type": "sub_type",
    "Monthly Revenue": "mon_revenue"
},inplace=True)
print(df.columns)

Index(['user_id', 'sub_type', 'mon_revenue', 'Join Date', 'Last Payment Date',
       'Country', 'age', 'Gender', 'Device', 'Plan Duration'],
      dtype='object')

In [7]:
mean_val=df["mon_revenue"].mean()
print(mean_val)

med_val=df["mon_revenue"].median()
print(med_val)

mode_val=df["mon_revenue"].mode()
print(mode_val)

12.5084
12.0
0    12
Name: mon_revenue, dtype: int64

In [8]:
summary=pd.DataFrame({
    "Data Type":df.dtypes,
    "Missing Values":df.isna().sum(),
    "Unique Values":df.nunique(),
    "Count":df.count()})
summary

                  Data Type  Missing Values  Unique Values  Count
user_id               int64               0           2500   2500
sub_type             object               0              3   2500
mon_revenue           int64               0              6   2500
Join Date            object               0            300   2500
Last Payment Date    object               0             26   2500
Country              object               0             10   2500
age                   int64               0             26   2500
Gender               object               0              2   2500
Device               object               0              4   2500
Plan Duration        object               0              1   2500